### ISSUE TITLE
Improper rendering on retina displays

### ISSUE THREAD

**Issue by andrewstart** [pixijs/pixi-tilemap#7]
When using a retina display (tested on a MacBook with Chrome), the tilemap example renders even more zoomed out, moves faster, and has small gaps between tiles (visibility of gaps changes as camera moves). <img width="927" alt="lineylines" src="https://cloud.githubusercontent.com/assets/1816311/15323210/e7baf3f2-1c0e-11e6-8e64-e0fa55911a65.png">

**Comment by ivanpopelyshev** [comment]
Its interesting that lines are not aligned with half-tiles and not whole tiles

**Comment by andrewstart** [comment]
Quick video: https://www.youtube.com/watch?v=M_vbfNer0PM

**Comment by ivanpopelyshev** [comment]
Is it fixed now, in https://pixijs.github.io/pixi-tilemap/?resolution=2&scale=1.4 ?

**Comment by andrewstart** [comment]
No, when the scale (or resolution) is not an integer value, you still have the lines.

**Comment by ivanpopelyshev** [comment]
resolution must be 2 for retina. I thought it will work for every scale :(

**Comment by Jarred-Sumner** [comment]
Some android devices use pixel ratios like `2.5` or `3.5`

**Comment by ivanpopelyshev** [comment]
Does it still not work?

**Comment by Jarred-Sumner** [comment]
I'm not actually sure, I was just reading through the open issues on this repo

**Comment by redgvin** [comment]
@ivanpopelyshev Hello, I have similar issue on android device with devicePixelRatio = 3, but it happens, only when part of map packed into sprite sheets (with or without tinypng). If each part of map is separate png or sprite sheets which includes only one png it works well. Any idea why?

**Comment by redgvin** [comment]
@ivanpopelyshev tested on different devices, it seems working well, I guess you can close an issue
